name: build-stg-command
on:
  repository_dispatch:
    inputs:
      issue_number:
        required: true
        type: string
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
    types: [build-stg-command]
jobs:
  build-stg-command:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      statuses: 'write'
      pull-requests: 'write'
    steps:
      - uses: actions/github-script@v6
        id: deploy-check
        with:
          script: |
            const mergeable = `${{ github.event.client_payload.pull_request.mergeable }}`;
            if (mergeable === "ttrue") {
              github.rest.issues.createComment({
                issue_number: `${{ github.event.client_payload.github.payload.issue.number }}`,
                owner: "monkukui",
                repo: "slash-command-processor",
                body: "ok",
              });
              return "can deploy";
            } else {
              github.rest.issues.createComment({
                issue_number: `${{ github.event.client_payload.github.payload.issue.number }}`,
                owner: "monkukui",
                repo: "slash-command-processor",
                body: "ng",
              });
              return "cannnot deploy"
            }
      - run: |
          if [[ "${{steps.deploy-check.outputs.result}}" == "cannot deploy" ]]; then
            exit 1
          fi
      - run: echo "hoge"
