name: build-stg-command
on:
  repository_dispatch:
    inputs:
      issue_number:
        required: true
        type: string
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
    types: [build-stg-command]
jobs:
  build-stg-command:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      statuses: 'write'
      pull-requests: 'write'
    steps:
      - uses: actions/github-script@v6
        id: deploy-check
        with:
          result-encoding: string
          script: |
            const mergeable = `${{ github.event.client_payload.pull_request.mergeable }}`;
            if (mergeable === "true") {
              github.rest.issues.createComment({
                issue_number: `${{ github.event.client_payload.github.payload.issue.number }}`,
                owner: `${{ github.repository_owner }}`,
                repo: `${{ github.repository }}`,
                body: `⚙️  Start to build stg image!
              Check the progress [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).`
              });
            } else {
              github.rest.issues.createComment({
                issue_number: `${{ github.event.client_payload.github.payload.issue.number }}`,
                owner: "monkukui",
                repo: "slash-command-processor",
                body: `❌ Cannot build stg image. PR should be mergeable.`
              });
              core.setFailed('PR should be mergeable.');
            }
      - run: echo "hoge"
