name: build-stg-command
on:
  repository_dispatch:
    inputs:
      issue_number:
        required: true
        type: string
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
    types: [build-stg-command]
jobs:
  build-stg-command:
    runs-on: ubuntu-latest
    steps:
      - name: Dump job context
        run: echo '${{ toJSON(context) }}'
      - name: Dump job inputs
        run: echo '${{ toJSON(inputs) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump issue_number
        run: echo '${{ github.event.client_payload.github.payload.issue.number }}'
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: 3,
              owner: github.repository_owner,
              repo: github.repository,
              body: `test comment`
            })
