name: build-stg-command
on:
  repository_dispatch:
    inputs:
      issue_number:
        required: true
        type: string
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
    types: [build-stg-command]
jobs:
  build-stg-command:
    runs-on: ubuntu-latest
    steps:
    - name: dump
      run: echo '${{ toJSON(inputs) }}'
    - name: comment test
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: `${{ inputs.issue_number }}`,
            owner: `${{ inputs.owner }}`,
            repo: `${{ inputs.repo }}`,
            body: `comment test`
          })
