name: build-stg-command
on:
  repository_dispatch:
    types: [build-stg-command]
jobs:
  build-stg-command:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      statuses: 'write'
      pull-requests: 'write'
    steps:
      - uses: actions/github-script@v6
        id: deploy-check
        with:
          result-encoding: string
          script: |
            const mergeable = `${{ github.event.client_payload.pull_request.mergeable }}`;
            if (mergeable === "true") {
              github.rest.issues.createComment({
                issue_number: `${{ github.event.client_payload.github.payload.issue.number }}`,
                owner: `${{ github.repository_owner }}`,
                repo: `${{ github.event.client_payload.github.payload.repository.name }}`,
                body: `⚙️  Start to build stg image!
              Check the progress [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).`
              });
            } else {
              github.rest.issues.createComment({
                issue_number: `${{ github.event.client_payload.github.payload.issue.number }}`,
                owner: `${{ github.repository_owner }}`,
                repo: `${{ github.event.client_payload.github.payload.repository.name }}`,
                body: `❌ Cannot build stg image. PR should be mergeable.`
              });
              core.setFailed('PR should be mergeable.');
            }
      - name: Get PR Number
        id: pr-num
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { number } = context.issue;
            return number

      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha 
