name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      statuses: 'write'
      pull-requests: 'write'

    steps:
      - name: Build stg
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: build-stg
          repository: monkukui/slash-command-processor
          issue_number: context.issue.number,
          owner: context.repo.owner,
          repo: context.repo.repo,
      - name: Build debug
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: build-debug
          repository: monkukui/slash-command-processor
